# Generated by Django 2.2.10 on 2021-09-02 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='polls.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='pollsession',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
