# Generated by Django 2.2.10 on 2021-09-02 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210902_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(default=datetime.date.today, editable=False, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='pollsession',
            name='date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
